# Generated by Django 5.1.6 on 2025-03-03 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_domanda', models.CharField(max_length=200)),
                ('data pubblicazione', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Opzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondaggi.domanda')),
            ],
        ),
    ]
