# Generated by Django 5.1.6 on 2025-03-04 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domanda',
            new_name='Question',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo_opzione', models.CharField(max_length=200)),
                ('voti', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondaggi.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Opzione',
        ),
    ]
