# Generated by Django 5.1.6 on 2025-03-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0002_rename_domanda_question_choice_delete_opzione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='data pubblicazione',
            new_name='pubblicazione',
        ),
    ]
