# Generated by Django 5.1.6 on 2025-03-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0003_rename_data_pubblicazione_question_pubblicazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pubblicazione',
        ),
    ]
