# Generated by Django 5.1.6 on 2025-03-05 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0004_remove_question_pubblicazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pubblicazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
