# Generated by Django 5.1.6 on 2025-03-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0005_question_pubblicazione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pubblicazione',
            new_name='data pubblicazione',
        ),
    ]
