# Generated by Django 5.1.6 on 2025-03-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0007_vote_question_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
