# Generated by Django 5.1.6 on 2025-03-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0008_remove_question_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_questions', to='sondaggi.vote'),
        ),
    ]
