# Generated by Django 5.1.6 on 2025-03-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0009_question_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
