# Generated by Django 5.1.6 on 2025-03-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0010_remove_question_votes_delete_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='data pubblicazione',
            new_name='data_pubblicazione',
        ),
    ]
