# Generated by Django 5.1.6 on 2025-03-14 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0012_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tempo',
            field=models.IntegerField(blank=True, default=600, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
