# Generated by Django 5.1.6 on 2025-05-30 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaggi', '0013_question_tempo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['testo_domanda']},
        ),
        migrations.AlterField(
            model_name='question',
            name='data_pubblicazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='tempo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(600)], verbose_name='Tempo per rispondere al sondaggio (facoltativo)'),
        ),
    ]
